In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,9,12,15,18])

In [3]:
myarr

array([ 3,  6,  9, 12, 15, 18])

In [4]:
myarr.dtype

dtype('int32')

In [5]:
myarr.size

6

In [6]:
myarr.shape

(6,)

In [7]:
myarr[0] = 45
myarr

array([45,  6,  9, 12, 15, 18])

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.size

9

In [12]:
listarray.shape

(3, 3)

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.shape

(2, 5)

In [19]:
rng = np.arange(8)
rng

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
lsp = np.linspace(1,50,2)

In [31]:
lsp

array([ 1., 50.])

In [32]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.69119873e-306, 7.56587585e-307, 7.56593017e-307],
       [1.24610383e-306, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22522597e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 9.79094971e-307,
        6.89804133e-307, 1.11261162e-306, 8.34443015e-308]])

In [33]:
like = np.empty_like(lsp)

In [34]:
like

array([ 1., 50.])

In [35]:
like.shape

(2,)

In [36]:
arr = np.arange(99)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
ex = arr.reshape(3,33)

In [39]:
arr.shape

(99,)

In [42]:
ex.shape

(3, 33)

In [43]:
ex

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
exx = ex.ravel()

In [45]:
exx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
exx.shape

(99,)

In [47]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [48]:
ar = np.array(x)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [51]:
ar.sum(axis = 0)

array([12,  8,  9])

In [52]:
ar.sum

<function ndarray.sum>

In [53]:
ar.sum()

29

In [54]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [55]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar.flat

In [58]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [59]:
ar.ndim

2

In [60]:
ar.size

9

In [61]:
ar.nbytes

36

In [64]:
one = np.array([1,255,3,4,5])

In [65]:
one.argmax()

1

In [66]:
one.argsort()

array([0, 2, 3, 4, 1], dtype=int64)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [70]:
ar.argmin()

8

In [71]:
ar.argmax()

6

In [74]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [77]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [81]:
ar.reshape(1,1,9)

array([[[1, 2, 3, 4, 5, 6, 7, 1, 0]]])

In [82]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [83]:
ar2 = np.array([[1, 4, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [84]:
ar2

array([[1, 4, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [85]:
ar + ar2

array([[ 2,  6,  6],
       [ 8,  5, 12],
       [15,  2,  0]])

In [86]:
ar * ar2

array([[ 1,  8,  9],
       [16,  0, 36],
       [56,  1,  0]])

In [87]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
ar2

array([[1, 4, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [89]:
ar*ar2

array([[ 1,  8,  9],
       [16,  0, 36],
       [56,  1,  0]])

In [90]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [91]:
ar.sum()

29

In [92]:
ar.max()

7

In [93]:
ar.min()

0

In [94]:
nds = np.array([1,2,3,4,5,6,7,8,9])

In [95]:
nds

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
nds.ndim

1

In [99]:
nds[0:8:2]

array([1, 3, 5, 7])

In [100]:
nds

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
nds.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
np.resize(nds,(4,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])